name: Docker

on:
  push:
    tags:
      - "v*"

  # workflow_dispatch:
  #   inputs:
  #     tagInput:
  #       description: "Tag"
  #       required: true

  # release:
  #   types: [created]
  #   tags:
  #     - "v*"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Determine version tag
        id: version-tag
        run: |
          INPUT_VALUE="${{ github.event.inputs.tagInput }}"
          if [ -z "$INPUT_VALUE" ]; then
            INPUT_VALUE="${{ github.ref_name }}"
          fi
          echo "::set-output name=value::$INPUT_VALUE"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            wiljonbolten/zapp:${{ steps.version-tag.outputs.value }}
            wiljonbolten/zapp:latest
